### PR TITLE
Update latest release section for 0.46.0 in website

### PR DESCRIPTION
**Pull request by Sreekala-Gopakumar**
https://github.com/eclipse-openj9/openj9-website/issues/366

Updated latest release section for 0.46.0 in website. Added performance highlights.

Closes #366
Signed-off-by: Sreekala Gopakumar <sreekala.gopakumar@ibm.com>

### CODE REVIEW

**Comment by Sreekala-Gopakumar** [comment]
@tajila @pshipton - I have updated the website section with the 0.46.0 content. Please check and let me know if any changes are required. Thanks!

**Comment by Sreekala-Gopakumar** [comment]
@nbhuiyan @vijaysun-omr @hangshao0 @mpirvu - Please check and confirm that the content is ok. Thanks!

**Comment by nbhuiyan** [comment]
Statement regarding VarHandle performance looks good to me.

**Review by hangshao0 — APPROVED** [review]
LGTM.

**Review by mpirvu — APPROVED** [review]
Looks good from my side

**Comment by Sreekala-Gopakumar** [comment]
Few more review comments were provided by Mark Stoodley. Incorporated the same. Made the structure of all the points consistent.

@mstoodle @nbhuiyan - Please check the following text and confirm that the changes are fine.

> - Performance of object and array allocation sequences on X86 is improved.
> - Performance of array copying sequences on X86 is improved.
> - VarHandle performance is improved.

**Review by nbhuiyan — APPROVED** [review]

**Review by mstoodle — APPROVED** [review]

**Pull request merged**
