### PR TITLE
Update latest release section for 0.46.1 in website

### PR DESCRIPTION
**Pull request by Sreekala-Gopakumar**
Created a draft file for 0.46.1 release with place holders for new content that is applicable for 0.46.1 release.

Signed-off-by: Sreekala Gopakumar <sreekala.gopakumar@ibm.com>

### CODE REVIEW

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - I have created a draft file as requested. Please let me know if any 0.46.1 release specific content has to be added. Thanks!

**Comment by pshipton** [comment]
0.46.1 contains some bug fixes, some of which fix crashes that occur with 0.46.0.
https://github.com/eclipse-openj9/openj9/milestone/59?closed=1

**Comment by pshipton** [comment]
We shouldn't remove all the highlights for 0.46.0 in order to announce 0.46.1.

**Comment by Sreekala-Gopakumar** [comment]
> We shouldn't remove all the highlights for 0.46.0 in order to announce 0.46.1.

Which ones should I retain?

**Comment by pshipton** [comment]
> Which ones should I retain?

All of them. Pls modify it to 0.46.1 and keep all the updates and perf highlights.

**Comment by Sreekala-Gopakumar** [comment]
> > Which ones should I retain?
> 
> All of them. Pls modify it to 0.46.1 and keep all the updates and perf highlights.

Done

**Review by pshipton — APPROVED** [review]

**Pull request merged**
